name: Monthly Eval

on:
  schedule:
    - cron: '0 0 1 * *'  # 毎月1日 0:00 UTC（日本時間 9:00 JST）
  workflow_dispatch:

jobs:
  build-and-eval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set GOOGLE_API_KEY env
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

      - name: Build FAISS index
        run: python ingest_and_chat.py

      - name: Run evaluation
        run: python eval_script.py

      - name: Upload evaluation results
        uses: actions/upload-artifact@v4
        with:
          name: eval-results-${{ github.run_id }}
          path: eval_results.csv
